server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xinyi?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 1610805383
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 20