
# 定义子文件后缀
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false

server:
  servlet:
    # session最大超时时间(秒)，默认为30
    session:
      timeout: 3600s
    #   指定访问路径
  # 错误页，指定发生错误时，跳转的URL。请查看BasicErrorController源码便知
  error:
    path: /error
  # 该服务绑定IP地址，启动服务器时如本机不是该IP地址则抛出异常启动失败，只有特殊需求的情况下才配置
  # address:
  tomcat:
    # tomcat的URL编码
    uri-encoding: UTF-8
  port: 8080
mybatis:
  # 配置mybatis的扫描
  mapper-locations: classpath*:mapper/**/*Mapper.xml
